[colors]
# 主色调：黑底白字
[colors.primary]
background = "#1c1c1c" # 一个深邃的炭黑色，比纯黑更柔和
foreground = "#ffffff" # 纯白色文字，保证最大对比度

# 普通颜色
[colors.normal]
black = "#323232"
red = "#FF3333"     # 与焦点环统一的红色
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ffffff"

# 高亮颜色
[colors.bright]
black = "#928374"
red = "#FF3333"     # 与焦点环统一的红色
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ffffff"

[font]
size = 12.0

[window]
opacity = 0.85
blur = true

[cursor]
[cursor.style]
shape = "Beam"
blinking = "On"
