# ==================================================
# Basic
# ==================================================

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on
set -g history-limit 100000

set -g escape-time 0
set -g focus-events on


# ==================================================
# Prefix
# ==================================================

unbind C-b
set -g prefix C-a
bind C-a send-prefix


# ==================================================
# Extended keys (foot / wayland)
# ==================================================

set -g extended-keys on
set -g extended-keys-format csi-u


# ==================================================
# Vi mode
# ==================================================

setw -g mode-keys vi
set -g status-keys vi


# ==================================================
# Pane navigation (vim style)
# ==================================================

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# resize pane
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5


# ==================================================
# Split window
# ==================================================

unbind '"'
unbind %

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"



# ==================================================
# Copy mode
# ==================================================

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key -T copy-mode-vi Escape send-keys -X cancel


# ==================================================
# Window style
# ==================================================

set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on


# ==================================================
# Status bar
# ==================================================

set -g status-interval 5

set -g status-left-length 40
set -g status-right-length 80


# ==================================================
# Plugins (TPM)
# ==================================================

set -g @plugin 'tmux-plugins/tpm'

# 基础优化
set -g @plugin 'tmux-plugins/tmux-sensible'

# 保存恢复
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


# Tokyo Night
set -g @plugin 'janoamaral/tokyo-night-tmux'

# ==================================================
# Tokyo Night
# ==================================================
#
set -g @tokyo-night-tmux_theme night   # night (default) | storm | moon | day
set -g @tokyo-night-tmux_transparent 1 # transparent background

# 风格
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare

# 状态栏
set -g @tokyo-night-tmux_show_music 0
set -g @tokyo-night-tmux_show_datetime 1
set -g @tokyo-night-tmux_show_path 1


# ==================================================
# Resurrect
# ==================================================

set -g @resurrect-capture-pane-contents 'on'

set -g @resurrect-strategy-vim 'session'


# ==================================================
# Continuum
# ==================================================

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'


# ==================================================
# TPM MUST BE LAST
# ==================================================

run '~/.tmux/plugins/tpm/tpm'
